//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NStudio.Language {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NStudio.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Akceptuj.
        /// </summary>
        internal static string acceptButton {
            get {
                return ResourceManager.GetString("acceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Akceptuje regulamin.
        /// </summary>
        internal static string acceptRulesLabel {
            get {
                return ResourceManager.GetString("acceptRulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj.
        /// </summary>
        internal static string aF1Tooltip {
            get {
                return ResourceManager.GetString("aF1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usuń.
        /// </summary>
        internal static string aF2Tooltip {
            get {
                return ResourceManager.GetString("aF2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edytuj.
        /// </summary>
        internal static string aF3Tooltip {
            get {
                return ResourceManager.GetString("aF3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Label.
        /// </summary>
        internal static string artistLabel {
            get {
                return ResourceManager.GetString("artistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string artistName {
            get {
                return ResourceManager.GetString("artistName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pseudonim.
        /// </summary>
        internal static string artistNick {
            get {
                return ResourceManager.GetString("artistNick", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Artyści.
        /// </summary>
        internal static string artistsButton {
            get {
                return ResourceManager.GetString("artistsButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Label:.
        /// </summary>
        internal static string ArtistUCLabelLabel {
            get {
                return ResourceManager.GetString("ArtistUCLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa:.
        /// </summary>
        internal static string ArtistUCNameLabel {
            get {
                return ResourceManager.GetString("ArtistUCNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pseudonim:.
        /// </summary>
        internal static string ArtistUCNickLabel {
            get {
                return ResourceManager.GetString("ArtistUCNickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień zdjęcie.
        /// </summary>
        internal static string changeAvatarButton {
            get {
                return ResourceManager.GetString("changeAvatarButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień język.
        /// </summary>
        internal static string changeLanguageLabel {
            get {
                return ResourceManager.GetString("changeLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aby zastosować zmiany, konieczny jest reset aplikacji. Czy chcesz zrestartować?.
        /// </summary>
        internal static string changeLanguageRequest {
            get {
                return ResourceManager.GetString("changeLanguageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiana języka.
        /// </summary>
        internal static string changeLanguageTitle {
            get {
                return ResourceManager.GetString("changeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło:.
        /// </summary>
        internal static string changePasswordLabel {
            get {
                return ResourceManager.GetString("changePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień dane.
        /// </summary>
        internal static string changeProfile {
            get {
                return ResourceManager.GetString("changeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miasto:.
        /// </summary>
        internal static string cityLabel {
            get {
                return ResourceManager.GetString("cityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Państwo:.
        /// </summary>
        internal static string countryLabel {
            get {
                return ResourceManager.GetString("countryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edycja profilu.
        /// </summary>
        internal static string d1Tooltip {
            get {
                return ResourceManager.GetString("d1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyjdź.
        /// </summary>
        internal static string dbCancelButton {
            get {
                return ResourceManager.GetString("dbCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa hosta.
        /// </summary>
        internal static string dbHostnameL {
            get {
                return ResourceManager.GetString("dbHostnameL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa bazy.
        /// </summary>
        internal static string dbNameL {
            get {
                return ResourceManager.GetString("dbNameL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        internal static string dbPassL {
            get {
                return ResourceManager.GetString("dbPassL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        internal static string dbSaveButton {
            get {
                return ResourceManager.GetString("dbSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia bazy danych.
        /// </summary>
        internal static string dbTooltip {
            get {
                return ResourceManager.GetString("dbTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aktualizacja ustawień nastąpi po restarcie programu..
        /// </summary>
        internal static string dbUpdateAfterRestart {
            get {
                return ResourceManager.GetString("dbUpdateAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        internal static string dbUserL {
            get {
                return ResourceManager.GetString("dbUserL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu EDYCJA PROFILU.
        /// </summary>
        internal static string editProfileLabel {
            get {
                return ResourceManager.GetString("editProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zaloguj się.
        /// </summary>
        internal static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Niepoprawna nazwa użytkownika lub hasło..
        /// </summary>
        internal static string logInError {
            get {
                return ResourceManager.GetString("logInError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu LOGOWANIE.
        /// </summary>
        internal static string loginLabel1 {
            get {
                return ResourceManager.GetString("loginLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu REJESTRACJA.
        /// </summary>
        internal static string loginLabel2 {
            get {
                return ResourceManager.GetString("loginLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyloguj.
        /// </summary>
        internal static string logOutLabel {
            get {
                return ResourceManager.GetString("logOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy na pewno chcesz usunąć te dane?.
        /// </summary>
        internal static string msgBox1Artist {
            get {
                return ResourceManager.GetString("msgBox1Artist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy chcesz zaktualizowac te dane?.
        /// </summary>
        internal static string msgBox1Profile {
            get {
                return ResourceManager.GetString("msgBox1Profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdzenie.
        /// </summary>
        internal static string msgBox2Artist {
            get {
                return ResourceManager.GetString("msgBox2Artist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dane zapisane.
        /// </summary>
        internal static string msgBox2Profile {
            get {
                return ResourceManager.GetString("msgBox2Profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przywrocono poprzednie dane.
        /// </summary>
        internal static string msgBox3Profile {
            get {
                return ResourceManager.GetString("msgBox3Profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Plik za duży. 64KB maks..
        /// </summary>
        internal static string msgBox4Profile {
            get {
                return ResourceManager.GetString("msgBox4Profile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowe hasło.
        /// </summary>
        internal static string newPasswordLabel {
            get {
                return ResourceManager.GetString("newPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stare hasło.
        /// </summary>
        internal static string oldPasswordLabel {
            get {
                return ResourceManager.GetString("oldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hasło.
        /// </summary>
        internal static string passInputLabel {
            get {
                return ResourceManager.GetString("passInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło.
        /// </summary>
        internal static string passwordFormTitle {
            get {
                return ResourceManager.GetString("passwordFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień hasło:.
        /// </summary>
        internal static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod pocztowy:.
        /// </summary>
        internal static string postcodeLabel {
            get {
                return ResourceManager.GetString("postcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Płyty.
        /// </summary>
        internal static string recordsButton {
            get {
                return ResourceManager.GetString("recordsButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zarejestruj się.
        /// </summary>
        internal static string registerButton1 {
            get {
                return ResourceManager.GetString("registerButton1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zatwierdź.
        /// </summary>
        internal static string registerButton2 {
            get {
                return ResourceManager.GetString("registerButton2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd rejestracji..
        /// </summary>
        internal static string registerError {
            get {
                return ResourceManager.GetString("registerError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odrzuć.
        /// </summary>
        internal static string rejectButton {
            get {
                return ResourceManager.GetString("rejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powrót.
        /// </summary>
        internal static string returnButton {
            get {
                return ResourceManager.GetString("returnButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz nowe hasło.
        /// </summary>
        internal static string rNewPasswordLabel {
            get {
                return ResourceManager.GetString("rNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powtórz hasło.
        /// </summary>
        internal static string rPassInputLabel {
            get {
                return ResourceManager.GetString("rPassInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        internal static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sklep.
        /// </summary>
        internal static string shopButton {
            get {
                return ResourceManager.GetString("shopButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Coś poszło nie tak..
        /// </summary>
        internal static string somethingWrong {
            get {
                return ResourceManager.GetString("somethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Utwory.
        /// </summary>
        internal static string songsButton {
            get {
                return ResourceManager.GetString("songsButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ulica:.
        /// </summary>
        internal static string streetLabel {
            get {
                return ResourceManager.GetString("streetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika.
        /// </summary>
        internal static string userInputLabel {
            get {
                return ResourceManager.GetString("userInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa użytkownika:.
        /// </summary>
        internal static string usernameLabel {
            get {
                return ResourceManager.GetString("usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stare hasło jest nieprawidłowe..
        /// </summary>
        internal static string wrongOldPass {
            get {
                return ResourceManager.GetString("wrongOldPass", resourceCulture);
            }
        }
    }
}
